# 공통
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always

logging:
  level:
    kr.co.inseok.mapapi: debug

resilience4j:
  circuitbreaker:
    instances:
      circuitbreaker-map-api:
        minimumNumberOfCalls: 5 # 테스트용 최소값 설정

naver:
  host: https://openapi.naver.com
  clientId: NLbQtjQTFrdtrLLb6_t1
  clientSecret: QgTQ1mXr0v

kakao:
  host: https://dapi.kakao.com
  restApiKey: b22b2bfafa0dda395d1cb98589b9346f